"""修改的内容

Revision ID: 4464954a58c8
Revises: d045aeb3d0b3
Create Date: 2026-03-31 17:43:35.722846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4464954a58c8'
down_revision: Union[str, Sequence[str], None] = 'd045aeb3d0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_extension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_extension_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_extension'))
    )
    op.create_index(op.f('ix_user_extension_id'), 'user_extension', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_extension_id'), table_name='user_extension')
    op.drop_table('user_extension')
    # ### end Alembic commands ###
