"""修改的内容

Revision ID: 4c33304686a8
Revises: ae85d3d773ab
Create Date: 2026-03-31 18:46:39.783857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c33304686a8'
down_revision: Union[str, Sequence[str], None] = 'ae85d3d773ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_extension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_extension_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_extension')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_extension_user_id'))
    )
    op.create_index(op.f('ix_user_extension_id'), 'user_extension', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_extension_id'), table_name='user_extension')
    op.drop_table('user_extension')
    # ### end Alembic commands ###
