"""修改的内容

Revision ID: 673dae236226
Revises: 758e80b1317a
Create Date: 2026-03-31 18:40:09.701340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '673dae236226'
down_revision: Union[str, Sequence[str], None] = '758e80b1317a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_extension_user_id'), 'user_extension', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_extension_user_id'), 'user_extension', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
