"""修改的内容

Revision ID: 758e80b1317a
Revises: 4464954a58c8
Create Date: 2026-03-31 18:35:34.498707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758e80b1317a'
down_revision: Union[str, Sequence[str], None] = '4464954a58c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_extension_user_id'), 'user_extension', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_extension_user_id'), 'user_extension', type_='unique')
    # ### end Alembic commands ###
