"""修改的内容

Revision ID: d3bc6d95e021
Revises: 4c33304686a8
Create Date: 2026-04-01 00:25:24.061987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bc6d95e021'
down_revision: Union[str, Sequence[str], None] = '4c33304686a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_article_author_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
